### ISSUE TITLE
第三方考试时钟调试时返回问题

### ISSUE THREAD

**Issue by XiaoGanCN** [ThisisHost/exam-clock#2]
用本地http-server搭建完成后的网站在调试时点击 
> <font color :gray>点击返回正常模式</font>

会直接跳转到 https://exam.thisis.host/ 而不是本地网站
这应该算bug吧
我对js一窍不通只能试着改一下 ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯ <s>(但确实能用了</s>

位置:search.js 第18行

<details><summary>具体修改</summary>
<p>

```javascript
//原版
ifwarn(SP.debug, "您目前处于科目检查(调试)模式。<u><a href='https://exam.thisis.host'>点击返回正常模式</a></u>");

// 修改后
ifwarn(SP.debug, "您目前处于科目检查(调试)模式。<u><a href=index.html onClick=”javascript :history.back(-1);”>点击返回正常模式</a></u>");

``` 

</p>
</details> 

<s>(还有，有没有考虑做release版</s>

**Comment by L33Z22L11** [comment]
fixed as
```js
ifwarn(SP.debug, "您目前处于科目检查(调试)模式。<u><a href='?'>点击返回正常模式</a></u>");
```

**Comment by L33Z22L11** [comment]
关于release版本的问题，整个项目已经部署在线上服务器，没有单独发行release版本的必要。
