### ISSUE TITLE
编辑科目的样式问题

### ISSUE THREAD

**Issue by gjhihihi** [ThisisHost/exam-clock#5]
编辑科目时若首字符输入回车再将其删掉会导致bug

**Comment by L33Z22L11** [comment]
按照操作未复现。

**Comment by gjhihihi** [comment]
输入回车前
<img width="931" alt="批注 2024-07-02 102153" src="https://github.com/L33Z22L11/ExamClock/assets/165488571/4cab0c4f-ea9a-4929-9f49-2c86b156a8b9">
输入回车并删掉后
<img width="914" alt="批注 2024-07-02 102154" src="https://github.com/L33Z22L11/ExamClock/assets/165488571/5630359d-338a-45fe-8b49-f4414eb9bec4">
